### ISSUE TITLE
`reference the id column of the recipes table from the ingredients table.`

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/sql-references-join#9]
via @jrhorn424 - "this is f*$%ing confusing"!

**Comment by gaand** [comment]
Why?

**Comment by jrhorn424** [comment]
Yeah, I was being bombastic. The developers got confused, and in trying to explain it (it made sense to me the first time I read it) I ended up confusing myself as well.

The problem for both of us was the "from" preposition. Instead of:

"reference the id column of the recipes table from the ingredients table"

I prefer:

"on the ingredients table, add a reference to the id column of the recipes table"

Another possible reason to prefer the second way: rails migration generators really like the "AddXToY" formula.

**Comment by gaand** [comment]
I think I'm okay with the latter if we keep some of the former. I want to capture that the constraint added to one table (child) also constrains the other (parent).
